FROM kyma/docker-nginx

COPY index.html /var/www/index.html
COPY jquery.min.js /var/www/html/jquery.min.js
COPY masonry.pkgd.js /var/www/html/masonry.pkgd.js
COPY imagesloaded.pkgd.js /var/www/html/imagesloaded.pkgd.js

CMD 'nginx'
