FROM kyma/docker-nginx

COPY index.html /var/www/index.html
COPY jquery.min.js /var/www/jquery.min.js
COPY masonry.pkgd.js /var/www/masonry.pkgd.js
COPY imagesloaded.pkgd.js /var/www/imagesloaded.pkgd.js
COPY bower_components /var/www/bower_components

CMD 'nginx'
