FROM kyma/docker-nginx

COPY index.html /usr/share/nginx/html
COPY jquery.min.js /usr/share/nginx/html
COPY masonry.pkgd.js /usr/share/nginx/html
COPY imagesloaded.pkgd.js /usr/share/nginx/html

CMD 'nginx'
